ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS conta_excluida BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS desativado_em TIMESTAMP,
    ADD COLUMN IF NOT EXISTS excluido_em TIMESTAMP;
