INSERT INTO categorias (nome, slug, ativa) VALUES
('Imóveis', 'imoveis', true),
('Autos', 'autos', true),
('Autopeças', 'autopecas', true),
('Celulares e Telefonia', 'celulares-e-telefonia', true),
('Casa, Decoração e Utensílios', 'casa-decoracao-e-utensilios', true),
('Esportes e Fitness', 'esportes-e-fitness', true),
('Serviços', 'servicos', true),
('Moda e beleza', 'moda-e-beleza', true),
('Artigos infantis', 'artigos-infantis', true),
('Animais de estimação', 'animais-de-estimacao', true),
('Música e hobbies', 'musica-e-hobbies', true),
('Agro e indústria', 'agro-e-industria', true),
('Vagas de emprego', 'vagas-de-emprego', true),
('Comércio', 'comercio', true),
('Câmeras e Drones', 'cameras-e-drones', true),
('Games', 'games', true),
('TVs e video', 'tvs-e-video', true),
('Áudio', 'audio', true),
('Informática', 'informatica', true),
('Eletro', 'eletro', true),
('Móveis', 'moveis', true),
('Materiais de Construção', 'materiais-de-construcao', true),
('Escritório e Home Office', 'escritorio-e-home-office', true);