spring:
  application:
    name: reusehub

  datasource:
    url: jdbc:postgresql://localhost:5432/reusehub
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    mongodb:
      uri: mongodb://reusehub:reusehub123@localhost:27017/reusehub?authSource=admin

server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000